### ISSUE TITLE
无法启动bot

### ISSUE THREAD

**Issue by RinTenicol** [benx1n/HikariBot#32]
try to launch the HikariBot
01-08 04:39:04 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "C:\HikariBot\bot.py", line 13, in <module>
    driver.register_adapter(ONEBOT_V11Adapter)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\driver\driver.py", line 69, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 72, in __init__
    self._setup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 85, in _setup
    self.setup_http_server(http_setup)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\adapter.py", line 76, in setup_http_server
    self.driver.setup_http_server(setup)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 116, in setup_http_server
    self._server_app.add_api_route(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 304, in add_api_route
    self.router.add_api_route(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 572, in add_api_route
    route = route_class(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 400, in __init__
    self.response_field = create_response_field(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\utils.py", line 90, in create_response_field
    raise fastapi.exceptions.FastAPIError(
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'starlette.responses.Response'> is a valid pydantic field type

**Comment by benx1n** [comment]
看起来似乎没有走一键包？请提供更详细的环境信息和复现流程

**Comment by RinTenicol** [comment]
> 看起来似乎没有走一键包？请提供更详细的环境信息和复现流程

换一键包已解决
