### ISSUE TITLE
Docker部署，Nonebot FastAPI ImportError

### ISSUE THREAD

**Issue by SinCerely023** [benx1n/HikariBot#34]
Docker部署HikariBot，更新后报Nonebot FastAPI ImportError。
删除image后重新pull未能解决。
Win10 21H2，WSL 2，Docker Desktop 4.16.3
```
C:\Users\SinCerely>docker pull 12hydrogen/hikari-bot:latest
latest: Pulling from 12hydrogen/hikari-bot
Digest: sha256:d482d7c1080223ccfbc7f330d131d2625d6365f99c0830fac73fa3a60ec8c135
Status: Image is up to date for 12hydrogen/hikari-bot:latest
docker.io/12hydrogen/hikari-bot:latest

C:\Users\SinCerely>docker run -d -p 10888:8080 12hydrogen/hikari-bot:latest -t TOKENTOKENTOKENTOKEN -i 526909856
0f29f02d12db31e3a8da888fcafcef4379f26e813e700b30173b4ad1c3df0c89

C:\Users\SinCerely>docker start -a 0f29
OK
02-12 03:38:18 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "/home/HikariBot/bot.py", line 9, in <module>
    nonebot.init()
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 256, in init
    DriverClass = _resolve_combine_expr(config.driver)
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 195, in _resolve_combine_expr
    DriverClass = _resolve_dot_notation(
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 184, in _resolve_dot_notation
    module = importlib.import_module(modulename)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 41, in <module>
    raise ImportError(
ImportError: Please install FastAPI by using `pip install nonebot2[fastapi]`
```

**Comment by benx1n** [comment]
fixed in #35
