### ISSUE TITLE
Docker部署，ocr报错

### ISSUE THREAD

**Issue by SinCerely023** [benx1n/HikariBot#36]
Docker部署HikariBot，启动时downlod_OcrResult()报JSONDecodeError
```
02-16 01:47:46 [SUCCESS] nonebot | Running NoneBot...
02-16 01:47:48 [ERROR] hikari_bot | Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hikari_bot/__init__.py", line 262, in startup
    await downlod_OcrResult()
  File "/usr/local/lib/python3.10/site-packages/hikari_bot/game/ocr.py", line 78, in downlod_OcrResult
    ocr_filename_data = json.load(open(ocr_data_path, 'r', encoding='utf8'))
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
02-16 01:53:10 [WARNING] nonebot_plugin_gocqhttp | [*QQ*ID*] 账号密码未配置, 将使用二维码登录.
```

收到群图片时pic2txt_byOCR()报NameError
```
02-16 01:53:59 [SUCCESS] nonebot | OneBot V11 *QQ*ID* | [message.group.normal]: Message *MESSAGE*ID* from *QQ*ID*@[群:*GROUP*ID*] '[*IMAGE*URL*]'
02-16 01:53:59 [ERROR] hikari_bot | Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hikari_bot/game/ocr.py", line 26, in pic2txt_byOCR
    if filename in ocr_filename_data:
NameError: name 'ocr_filename_data' is not defined
02-16 01:54:02 [SUCCESS] nonebot | OneBot V11 *QQ*ID* | [message.group.normal]: Message *下*一*条*消*息*
```

Windows部署，env.prod中使用如下ocr设置时，相同图片可以正常触发查询。
```
ocr_on = true
ocr_offline = false
ocr_url = http://mc.youthnp.cn:23338/OCR/
```

Win10 21H2，WSL 2，Docker Desktop 4.16.3
Docker image: 12hydrogen/hikari-bot:latest
sha256:0a16f81294d70505e5bf54ea84622705b1f57236321e0bfc630acc6781c249d9

**Comment by benx1n** [comment]
看起来是启动时从服务器拉已记录的OCR结果出了问题，ocr_offline 设置为false即为不启用本地匹配，尝试重启过了吗

**Comment by SinCerely023** [comment]
重启无效。docker image更新后问题消失。感谢！
